### ISSUE TITLE
unwanted match cannot be removed

### ISSUE THREAD

**Issue by gherson** [MaLeLabTs/RegexGenerator#10]
Entering examples on the website (http://regex.inginf.units.it/) went smoothly until my 9th example, `1c==guess_count`.  Why can't I enter that as a matchless example?  I cannot remove the unwanted, automatic match that appears (on the entire string).  

(Also, I was not able to submit the above via the website's Feedback button: there was no response to clicking Send.)

**Comment by ftarlao** [comment]
I'll look in to it and update this thread, ASAP. I suppose it may be related to the web interface part, that is not part or released with the RegexGenerator project which covers only the engine. But we will see... Please, can you also provide in a 'comprehensible' way (e.g. list of, text->text_to_extract1,.. or text->(x1,y1),(x2,y2) where x,y are start and end of the text segments to extract)  other examples for the dataset you tried to submit?

**Comment by ftarlao** [comment]
You can also enter the other dataset rows in the interface, export the json/csv (don't remind the format) dataset and attach the dataset here in this thread.

**Comment by gherson** [comment]
Here is my export from the time of the error:
```
{"examples":
[{"string":"guess_count == 1","match":[{"start":15,"end":16}],"$$hashKey":"00V"},
{"string":"guess_count==1","match":[{"start":13,"end":14}],"$$hashKey":"00P"},
{"string":"1c==guess_count","match":[],"$$hashKey":"011"},
{"string":"1c == guess_count","match":[],"$$hashKey":"017"},
{"string":"1.==guess_count","match":[],"$$hashKey":"01D"},
{"string":"1.0==guess_count","match":[],"$$hashKey":"01J"},
{"string":"1==guess_count","match":[{"start":0,"end":1}],"$$hashKey":"021"},
{"string":"1 == guess_count","match":[{"start":0,"end":1}],"$$hashKey":"01V"},
{"string":"guess_count==1c","match":[{"start":0,"end":15}]}]}
```

The problematic example is 3rd from the top.  Thanks.

**Comment by ftarlao** [comment]
I think that the problem may be related to the way you insert the examples into the web interface.
Firtst try, 

I suppose you performed cut&paste from a source doc and that you copied also the format/style infos, then performing CTRL-V on the RegexGenerator web interface may cause the paste of "HTML-stuff", with the text (I suppose in the form of a piece of dom), directly into the text field... I fear this may bypass our sanitization algorithms. Please try inputting the problematic text by performing CTRL+SHIFT+V  (instead of CTRL-V), in this way should paste only the text with no formatting infos.

Or perhaps, you copied the examples from part of previously inserted examples, directly from our interface, this may create or cause problems.. because "internal" invisible informations may be copied. I suggest to use an external text editor to copy from text portions.

Later I'll try your dataset directly, but I need few hours...

**Comment by gherson** [comment]
Good call! Control-shift-paste is good to know and fixed the problem, thank you.

Next question:  Why might https://regexr.com/488jl say the regex I got out, `(\d[^ ])*+\d`, is invalid ("Nothing to repeat")?

**Comment by ftarlao** [comment]
because the regex is in Java/(similar to..)PCRE format, in the upper/left side of the regexr.com tool you can change the expected regex syntax from Javascript to PCRE.

**Comment by ftarlao** [comment]
The web version of the RegexGenerator engine (is a demo and has computational constraints) performs a quick search for a solution. It also uses one single (always the same) random seed in order to make the solution search deterministic. 
In order to randomize the search a bit and try to find new solutions, you should try adding other examples or changing their order. 

The released engine, that comes with no Web UI, is able to perform very long searches with more jobs (you can fully configure depending on your hardware) and to change the random seed... but it requires to be an expert programmer/advanced user in order to install and manage it.

**Comment by gherson** [comment]
Interesting, thank you, will remember next time I need a complicated (to me) regex, which may be shortly.
