### ISSUE TITLE
Anyone aware of javascript port?

### ISSUE THREAD

**Issue by geertbrit** [MaLeLabTs/RegexGenerator#4]
Is anyone aware of a javascript port of this code?
If not i might take a crack at it.

**Comment by adelorenz** [comment]
For now, there are no javascript port of our library.
This is due to the fact that the javascript engine for regular expressions does not use possessive quantifiers. For more details:
1. [Inference of Regular Expressions for Text Extraction from Examples](http://machinelearning.inginf.units.it/publications/international-journal-publications/inferenceofregularexpressionsfortextextractionfromexamples)
2. [Regular Expression Matching Can Be Simple And Fast ](https://swtch.com/~rsc/regexp/regexp1.html)
3. [Regular Expressions: Catastrophic Backtracking](http://www.regular-expressions.info/catastrophic.html)
4. [RegexGenerator++ F.A.Q.](http://regex.inginf.units.it/faq.html)
