### ISSUE TITLE
Tests offered are insufficient to evaluate the effectiveness of the software

### ISSUE THREAD

**Issue by topicscout** [MaLeLabTs/RegexGenerator#5]
The goals of the academic paper published were VERY interesting. This got my attention and I thought it was worth looking at.

But there are problems in what is provided.

I do not see any extensive test data and the results of creating regular expressions with that test data here in this GitHub repo.  Instead, the only test I saw - DataSetTest.java - is very, very simple. This is not adequate, not even for software produced by an academic institution.

It is not even the case that the test properly illustrates how one would use the software.

So here is the issue:

The kind of software described in the academic paper could be quite useful, but to be evaluated, there should be tests that use various datasets and then show the accuracy of the discovered regular expressions. In addition, those tests should make it clear to an outsider how one would use the software.

If you want your software to be used,  you should make it practical to evaluate and adopt.

**Comment by ftarlao** [comment]
We made this code publicly available only because we received numerous requests by people who read our academic papers. We are not able to provide support or extensive documentation. 

You may want to have a careful look at [RegexGenerator wiki](https://github.com/MaLeLabTs/RegexGenerator/wiki), though. You will find a detailed installation walkthrough along with the results of a sample execution.

You may also want to note that this is only the code of our tool. It is not the code for running the experiments in our academic papers. It does not even include the datasets. If you are interested in the datasets, you can find in our lab web site the subset of the datasets that we could release publicly.

Thanks for your interest.
