### ISSUE TITLE
It seems not support multiple language

### ISSUE THREAD

**Issue by SUKI-Huang** [MaLeLabTs/RegexGenerator#8]
I use simple example to data set only 5

王安齊：你好，草擬馬。[0,3]
豬豬：我是河馬王ㄎㄎㄎ[0,2]
孫紫晴：不會 麻煩你了 謝謝[0,3]
王儀婷：安卓是真的都蠻好用的就是[0,3]
羅思慶：哪條不爽 註解掉就好了[0,3]

but it can not generate result

**Comment by ftarlao** [comment]
Thanks for your feedback and interest in out project, the engine is able to manage Unicode text. Please note that our engine by default provides \w, \d as building blocks (that makes quicker to find solutions with alphanumeric strings)  but we have not added \p{Han}  (?? I don't know exactly the class for chinese characters). My first suggestion is to grow the size of the training, to try bigger population sizes and more generations. Please provide your data in json format (as described in documentation), and we'll inspect your case in the future. Thanks to the fact our code design is quite modular, you can also write(or improve) a TerminalSetBuilder in order to increase the number of building blocks (characters, symbols, separators) that are taken by looking at the provided examples (but you should consider that bigger an alphabet size is, bigger the solution space to explore)

**Comment by ftarlao** [comment]
I forgot: Thanks for your feedback and interest in out project :
